### ISSUE TITLE
ArgumentException: NetDataReader cannot write type SimpleCharacterResult

### ISSUE THREAD

**Issue by websox** [insthync/LiteNetLibManagerSimpleCharacter#1]
ArgumentException: NetDataReader cannot write type SimpleCharacterResult
LiteNetLib.Utils.NetDataWriterExtension.PutValue (LiteNetLib.Utils.NetDataWriter writer, System.Type type, System.Object value) (at Assets/Plugins/LiteNetLibManager/Scripts/NetDataWriterExtension.cs:205
SimpleCharacter.SendResult (SimpleCharacterResult result) (at Assets/Scripts/SimpleCharacter.cs:86)
SimpleCharacter.FixedUpdate () (at Assets/Scripts/SimpleCharacter.cs:173)

**Comment by insthync** [comment]
Fixed, I use wrong data types for net functions.
